// filepath: resources/js/app.js
// ...existing code...
// ...existing code...
import '../css/app.css'; // Make sure this file exists
// ...existing code...
// Entry point for your JavaScript
console.log('Vite is working!');
// ...existing code...